spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: abc
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8060