spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/test-micro
  cloud:
    gateway:
      httpclient:
        max-initial-line-length: 8192
        max-header-size: 16384
        max-chunk-size: 20971520
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/customers/**, /api/v1/address/**
        - id: product-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/products/**,  /api/v1/option/**, /api/v1/category/**
        - id: order-service
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/order/**, /api/v1/cart/**
        - id: notification-service
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/notifications/**
        - id: review-service
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/reviews/**

server:
  port: 8222