spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/realms/test-micro
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/customers/**,/api/v1/address/**
        - id: product-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/products/**,/api/v1/option/**
        - id: order-service
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/order/**,/api/v1/cart/**

server:
  port: 8222