spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: product-service

application:
  config:
    s3-serviced: http://localhost:8090/api/v1/s3-service