spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5432/review
    username: abc
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8020