spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: s3-service
aws:
  accessKeyId: ${ACCESS_ID}
  secretAccessKey: ${ACCESS_SECRET}
  s3:
    bucket: ${BUCKET_NAME}
server:
  port: 8090

